### ISSUE TITLE
why based on geospatial?

### ISSUE THREAD

**Issue by januz** [rocker-org/binder#28]
Thank you for providing this (and all the other `rocker`) image(s)!

I wondered why the `binder` image is build on top of `geospatial` and not on `tidyverse` or `verse` as, from my perspective, adding the possibility to use `Binder` is a more fundamental feature that might be important to everybody interested in reproducibility, but not necessarily in geospatial analysis tools. Furthermore, the geospatial tools add quite a bit of image size.

One can obviously just copy the code from the `binder` Dockerfile and add it to a project's Dockerfile. It just adds a lot of code that might distract from the adjustments that are specific to the project at hand.

**Comment by cboettig** [comment]
Good question!  

I find there's really not that much incentive to keep images very small vs having packages pre-compiled and system libraries pre-installed.  Binder takes a few extra seconds to download those extra MBs and much longer to compile those packages from source.  Spatial libraries can be particularly hard for users to install given the system requirements -- (I believe the binder's default images also provide those big spatial libraries like `libgeos-dev` pre-installed for the same reason).  This means less for the user to have to figure out and configure if they want to use those libraries.

**Comment by januz** [comment]
Thanks for your response! That sounds reasonable. I myself don't mind having the extra MBs, just thought that some users might object...

**Comment by HeidiSeibold** [comment]
I like issues. Had exactly the same question and found that it has already been answered. Are there any plans on creating a more slim version?

**Comment by cboettig** [comment]
@HeidiSeibold great!  Yeah, @noamross and I have been talking about strategies that would allow a more modular approach, but would need a significant overhaul of the versioned `tidyverse`/`verse`/`geospatial` stack!  But since there's such a range of packages individual users might need our current approach has been to suggest users for whom image size is mission critical simply build a custom image with some copy/paste from our current stack.  For most users we find big images are a nuisance but still preferable to having to do custom builds. (Particularly on binder where that can result in very long waits for stuff to compile).  

Newer images are going to be even larger as we see more demand for doing ML + geospatial, particularly on an image that supports GPU libraries, so that's also driving the motivation for a more composable stack.

**Comment by HeidiSeibold** [comment]
Thanks for the answer!

> But since there's such a range of packages individual users might need our current approach has been to suggest users for whom image size is mission critical simply build a custom image with some copy/paste from our current stack.

I should be able to manage that :wink:

**Comment by cboettig** [comment]
cool, ping us if you hit issues because that'll help me when I get back to making it more composable (I didn't mean to be flippant about copy/paste, sometimes there's unexpected dependency issues from elsewhere in the vertical stack that make that less trivial than it sounds).  

Also, I shoulda mentioned -- for projects that don't depend on packages that have a lot of external sys reqs (like geospatial), the 'default' [binder setup](https://mybinder.readthedocs.io/en/latest/introduction.html) without a custom Dockerfile usually works out of the box, so the rocker image is kinda catering to the heavier cases anyway I think.

**Comment by HeidiSeibold** [comment]
Thank you! :sunflower:
